language: java
dist: trusty
addons:
  sonarcloud:
    organization: antop-dev-github
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean package jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY
  - mvn coveralls:report -DrepoToken=$COVERALLS_TOKEN
notifications:
  email: false
  slack:
    secure: ude2DR8FlKBXitZiKcK7VPM6k2oHNZf8+NwMfYKktntSyvFMucAXl+RabY5mtTtpZkLlak9tkjfI1sWbfahTeeR4JkkgidHTtoQOeEPusz7rwNzzGEmuo9/g0mh+K4A2JBsJQMa8gwZ/kXAqEdUTo8H733yrZf3xEL8JGwuVZ+X1p3K5z+jMDi8zCYhO6uIOSOlOviL8yYRvTV+W4cyQgqLfdHQBFJKKcfvZjrv2hmWJSZ5qMzms8ZhNyfU+7E2pbZZ8eMldDOhUFLhC+RJvyC+j94Jd3y+njK79QVGgsw4jYK8UBXLVqcOYyjqJyqFz9u7dqDtwLXgKPPjE5fqDWHc9/eGK/d80yZy/G3/40qn029lc/eli5tEaTyYHkI1Hbps6+3j/grSZqMjinboIjxTQd8p9XO8Q/X5WcRiY+QRfMC6VhCn1cYxAv1EnzSQcPtP9tqwu6+lQcRWSHH1kf+ZD7ndG3SjAv3Up44CNnMRu1OLdABL20Jll3zDKQjMUAF2UZWJslcikkd+NoJwX0Jr3tsvNR36YEmjy30Q7fEbMBuaeNIEJq+MNQvHJRlnk3fZ8NImyaitUYCBZ7kPmb2jr369FQEDsKpZ3QT77QT3boY1T+5avERkx2kq5JVOmG5ztkgsGsYIGf9yvklgBfe5iHPULG7MK2BQFvTxL//Y=
