language: java

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: "mvn test -Dmaven.javadoc.skip=true -B -V"
