language: java

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report