language: java
dist: trusty
env:
  - COVERALLS_TOKEN
      - secure: WLJ3q3Ij4V/N/wNs1+U4hizSuN/2MtOCu8iGhLTwRx6q7AriWn5YD22MygAsJDs8sWv81zlH8RdP4IWE/ME1TOGTWVYjsLE4Nw6vrdC4LgQiqK3y+h/3DSDtnh06L6CgNTe04WC9iAR5kdV6sPr/sJfODDmqQnJ+35wJHqKun7FtyFLxx0PmK3BZIEuQaPUD9DRlRMFiTCGPfV+Xq0FN16kMpd+vdtOXWPu2EI8HXLGcydHuIO2pWMJ9mHiTDOIuYIwqqVTifElZ6xQY4zez3YZ1Y2eXq/YDjT3U8hY/BOQpcicoxqiX3ThlX+9RdtKcGpj9aH/QFmejO4yft5qxHDryygMpTbgtMgwH4AH5Euv+v5R6txYJwKevFk2Lx5N47vQb6wBeF7s+HWmIgpu/MfaW6rTN2tYaS5oatvTwXZ5pS9jjadJDa91Slg0f/sbJPXMpHSWr2J4YIYKKmHahWFL1qqTNaMH2BURRot5qnJpobwWA1OChqsAZS8N2KFrjUktUEvM9taS+qx0QoIczy84lixWd6mqavQZ8gfFoAdLjUGtLasztowG+agkqrvSgz7jLuTBA4xL85rzUQaunh1kvKQuaBrLjZ9a/s3IOMcU85oLumEIdmrejLFCb6x9fGkajSiC7HDGfvpSNHbjS0pRebbAg7Z+08rj+0X7Mk4M=
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn clean coveralls:report -DrepoToken=$COVERALLS_TOKEN
notifications:
  slack:
    secure: FIrx7XSyRUCDWygwegKhkZnEUIRB1hOOrw5BEXC4t094wKSPyi24zHC+TX2nU0FKs9YrmB7TIOYssfUCmirQcRavbEiNOFGtsO29+7SJ+AawtIWyRlOYNiah9tryTSGf/gENaYs0DLqPG0E7WW/NblRpTolNeTba0gTVnkhgY1CvuLshWY4sKWBkhGcViIDfOGTl8GGD5L287hegjstFmoZJT8J1gNrSGXL91ULn+EAiOuH0vgoNaq7S78ZlPYIVTyehBRHUcVLgXuW8yswLArguyqShocpLFb46WIzWm/kh/HskkmGTEnw7LYVp5MrIcRmNCbe6rhMheE38A6WllmU+cPTE2pOCpLRBHcjByZ8dqd6qS8YlVR/q8aSYZMCtu7ViIPVWXOnuggMjP2ebrd3KGC/9fY47hyXAPb7qx8ifVQdKXggAlRkgawlfDNVkip/0ELZTtexME+VNESESwITcOXwhZUDikOcEgeilt+8XeOhbALQ69Ek97DmvpaanyMLakWGWDE2IA+CNRUXsKMmb2Kx/tMrjRNdkUc5JS2eTjqFlznIMHBKKn4NO7QrXtoRaC2IXKAqPdjgqof+6HrOM6QYc+Ik8OWmsZz6EGG6Y55WRg2A9O77cGyRqx8PaBUfSeP5TaufU8LD1t37qoRcg6Lcm1uxXx9PuHrwoq4k=