language: java
dist: trusty
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAL_LOGIN
  - mvn coveralls:report -DrepoToken=$COVERALLS_TOKEN
notifications:
  slack:
    - secure: KH8z/un/q8gbYnI9REwaande3ukpwD3OgFaun7DG/1KV0W2SnJkdUI6U0NH1uzUCCY8ZbAbJ+HfrTNwWrh1sDzJKk8UbWFmM7douA9DFBISBfHVzhdg6HUqEbvw+H3KAp7DIo95IcsMLIK6YLcaicAFKop8Q67neFlpq8t5LiPQh+0ZsfIyc5shiMNEPtKTcZjXryS3RwvBGn8PZpPhTcybTeLmlz8siPn2zaRMawX/K2hjW41JNjluQovL4xXuzAW6YQGnGHM2DRP/U6TQ8VcW0j0gamNm49hqAcWwzZ14OsoWvFbEVDQrTXVKAq0WCTUbm1kJSUTNAQVoKvCjCZXY5paoL7FMY5ClII/Z9lN00UcQcNkh49N37KVZjiud9/DLn7ihXWKKpoi997ayDLSKtgDo8EqKGYS8RjyzPw0JFVLgjs7L+z9+IHETr0vnK6JwkhOQNxeECYN9jjGEdvphBf3J0WfY29s4fRnv4CXemM1FAdbaqNmiCphJRbHz6Y49n+kZZnxFOWLl7rw1nqnnkPHMgJbdEexQvt1Vb9qgFJBRBVhiR+wLlqRbnl1+1YdsMXlCfbx8nhSQ7J69cxOAXutupPXkApqkdM+CEqOkxU2Y2qzsu4QnwK31kuG6GRC7yFCzUu2nGDI56B2q3B6eu5KOHZqBPK2rvxZ2L6KU=
