language: java

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - .autoconf
    - $HOME/.m2

script: "mvn install -Dmaven.javadoc.skip=true -B -V"

notifications:
  email:
    recipients:
      - antop@naver.com 
