language: java
dist: trusty
addons:
  sonarcloud:
    organization: antop-dev-github
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean package jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY
  - mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
notifications:
  email: false
  slack:
    rooms:
      - secure: fLzT5G+WdO9qwo/c7aLg25xtFk9CSgHYXbv5YbkKuExHS2W2FwoJ/GFCvvhCrXfImLosW7reIOv+QABIhtGv46ci7hOaK6aMwJhWZ4tAZLi2nawhpkO7d6ktfeUsiyqHp5MpdwYGExM/m+h+B7a549NjK83lwhvkD8Y8RSls2pv0SPkKYRS34SuUACIpsZJ1zqqVivNho5KQCBP7Jg/wV9G9M+odOldi2FX3dUm3RjekDK68FPe54XxPpZuhLCduYa6ewKXuX4NpDvMjPL0uYgutfHJjtvmuowKNHX2WpYP2AZc0Uso9MvK/j+b6CDXoNn7DDdVI9G/Uk87+l1zAnCC0z2tYpw7C5+jk1xpnXBUUPtgogb4c5EuMxWlA6o4pplgV5tnIgpJwPlMxAO+AMFqbutbzdmFnTQ+kxE448Qiqk83VU/S7h1u1h08UWGBXKV2Q7Dc3ZjKp63CCXZpgSmwRCV9SVVSnTyTPtes2iNbsDbRO2c+BYSOGcKIh2JssNSyZpOeR6HR8IuI7GPgg522vQeyNsWVwcMX/wcWQYlliNjs8Y4WjAKlGzxW9H95VE9vymRHLtABti+N/4Gd/4scE21FlpyKuErXE28rReHnGroKlZ266rzaOcc/4btmRURnrQY/vs/4VFFN/QK2Zzshr/zX2vaF4jJEY9GMrd+s=
