language: java
dist: trusty
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report -DrepoToken=$COVERALLS_TOKEN
notifications:
  slack:
    secure: "XnT5Ro1tNYwfCWYwT0QrdPAZ9Kk/fJnrgU3Dvtsi1fpPOu3YoIZL5Px63AGaTRVIM2kfpV0olmtFUBfq03AdDkLrGaURpNAYhQRsdONbO6xrBcgxWE3XCPIIeQQuUpf3xuh0P1ml2a5rdZ8Ruv4ntcdf1EGvxgbsWVLmzOVAZem8mWaGpcTvPjtm4fSHgv4thu1+AWGKootJryt4eKoUF3gcHLsFsURw/AznWrYo7F4oKRXK/UOJC0nx0rwr4EhkyIjd7ofW7kR1csWttNKUzl4TTltKQAj483/fgex79RSyIzuC87S5cM0bKYtEk4T8x0vlOKZkxG2VkoQduA2nld4pyno4HIf1iSqZCCfRZeu/bZquyDezyQP1DhjSDyFvxYf6QykZTZVgnH56fI0zc8/CCxo5TEFzWXnXuMYWpmZRkNdf+XSYOcVb/QIsUnQWrmF1Fd4ZlSbRsjmu5rU+e07I07fp/x77H7WjlwSmhOyJRf7b200irR+IsT/j+rC5ictF4BV2h60eKkior7vjhVQqMic92/n8juzlglACJ13vY+J+ZwRcHVA/EZy+kL9rlYqvjG8Z4E+oobmMqLwq5s96GPKYI25oLL4TeZMXDdPL9BbHi3A+tvGiZflaHJnQGdX9NcdNWXX5LwIXcMrcJLjKvuUdstD1L58xNJPw5jg="
