language: java
dist: trusty
addons:
  sonarcloud:
    organization: antop-dev-github
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean package jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY
  - mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
notifications:
  email: false
  slack:
    secure: uWHimJkp/Kw/3wJwTSRSHVwLYSJLSjw0oa+RrJlQxSF0Uw+q4aTXcfzB42V84WOX1Ym9G8RsKZspFiW/tcBfCE2dbhp6A6hkDricV8RopkXZt8u+HodRuR0WlQGUjg980hTnCsm7Uqu7FX3l3+lCdh9Mjc/iONIwKupLQVcBPCqKfJbnjbhoLX7r6hkheVjthiTk9lJ5xdMTvkg7t3GtQ+7asIl8VLFPB+IKqcP15p6DUj057atuMpXIiu/qizAYQ3gd+ZsKS0riQQZZ3z4I6u+z25VvbpJ6bG15a2EH2soINrxRSIsJ0PdSHjWVOCEDUHLIaicHrbCxab+RajlG0ySd56bO/teEuB2ZeG3LRlLsUYWXDUk/UeDMb8vyMjJqjv5/x1tJuaYtObBlFKY6zDiskZxOHCNt3pfCJ7XVGUd5YQgI2p/tXESXkaOsdvqfYv5XjaYFgY9fWzzPzet1UmOeeRVrlltIpDq/e8GBeS3wApW+JsUFepg7hzj/Gdivtbr9560P6sDfNw/Av2/9x7ZQBX5ffMvyN+7Pbu3FlPlk83wyqPQga9HlF1IOmtj0w9XTtQc6XjCLFkXoxO3nTIHlburrtgzFNUiL7UFCCgs1jsh3kqBI/T4n26EKwRK4kk27ZztLjF/bYeyiX84TKFUxOpBqybZc9BPE5VtLXJk=
