language: java
dist: trusty
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
  - "mvn test jacoco:report"
after_success:
  - "mvn clean coveralls:report -DrepoToken=$COVERALLS_TOKEN"
notifications:
  slack: any-study:BvfF5AJsm1wdcEG5l41UuoUj

#    secure: rb+b+kuElOe7JnFJu8lPI6hETYGJLrm7jITTiLvXg+YweDcPf9DxZQNaR77k9nO44+MSL6DgEgflmqYxURAkPYss8Ga/Np/aBCrvwT+AjuTb610rxT4aMiLFPSL7+pT9NozzGg41Bkx5BHkNr3nkYvmWLPTVlSjUpPymh0ccXT+yEZkUupYTLmLe3jKForb3MfilpLAl1nIcZvZkVAAwdFcwBDeTTmXBqXi4uAAdDU8Q058dsigjpYTp/tPxHCY2feNprdaGF5sAWVxLenSrmKsJv82t2dvqq2PXRWUaI17G0VHR40FqRCbNKzB/XwKMK5i8jlCF3jp83haiMy2DKipKLMQCNheSFfn5IFBrcdy8Rf0AdDKlhAnE1m9F6qtnD5GhoHmeE28Dsd8ElOfkeYEZEhPGte7X7y/FDg+NETTn6VNDF4G9z8CKJRscK0ROaWAJLuMx7QRT81EINP9HmIJa9lFuvxwVvnyWxiKyJz8dk0cpvxWf3cT06/7oYyRulEZJajkqDYG3y7AayJ5VsIBuprEh0vrs32924HimCSZD+uHHDZBcMyyUxVKxe1BN6gBZmtfF3G85D/1yYPLHq2S3jLI1oDLGTKVPDh3ykqXNWAtZkLld/1mIdag/sKN1Ps7bpmePQ45Yud1sKL41tC0bjvF+xwGNsy78TGQpbfI=
